# GitHub Actions Workflow to deploy the Poker Dice game

name: Deploy Poker Dice to GitHub Pages

# This workflow runs on pushes to the main branch or when manually triggered
on:
  push:
    branches:
      - main
  workflow_dispatch:

# A single deployment job
jobs:
  deploy:
    # Use the latest version of Ubuntu to run the job
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository's code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Create the production config.js file from GitHub secrets
      - name: Create config.js for Poker Dice
        run: |
          echo "Generating config.js from secrets..."
          echo "window.APP_CONFIG = {" > config.js
          echo "  API_KEY: \"${{ secrets.MULTISYNQ_API_KEY }}\"," >> config.js
          echo "  APP_ID: \"${{ secrets.MULTISYNQ_APP_ID }}\"," >> config.js
          echo "  BASE_URL: \"https://sarcastichedgehog.com/pokerdice\"" >> config.js
          echo "};" >> config.js

      # Step 3: Deploy the contents to the gh-pages branch using your PAT
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # --- THIS IS THE CRUCIAL ADDITION ---
          # This tells the action to use your Personal Access Token.
          # The name 'GH_PAGES_DEPLOY_TOKEN' must match the secret name in your repo settings.
          token: ${{ secrets.GH_PAGES_DEPLOY_TOKEN }}

          # The rest of the configuration
          branch: gh-pages
          folder: .
          clean: true
