# GitHub Actions Workflow to deploy the Poker Dice game

name: Deploy Poker Dice to GitHub Pages

# Run this workflow every time a change is pushed to the main branch
on:
  push:
    branches:
      - main

# A single job called "deploy"
jobs:
  deploy:
    # Use the latest version of Ubuntu to run the job
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository's code so the workflow can access it
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Create the config.js file from secrets
      # This is the crucial step that securely injects your API keys
      - name: Create config.js for Poker Dice
        run: |
          echo "Generating config.js from secrets..."
          echo "window.APP_CONFIG = {" > config.js
          echo "  API_KEY: \"${{ secrets.MULTISYNQ_API_KEY }}\"," >> config.js
          echo "  APP_ID: \"${{ secrets.MULTISYNQ_APP_ID }}\"," >> config.js
          echo "  BASE_URL: \"${{ secrets.MULTISYNQ_BASE_URL }}\"" >> config.js
          echo "};" >> config.js

      # Step 3: Deploy the contents to the gh-pages branch in the /dice folder
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # The branch the action should deploy to.
          branch: gh-pages
          # The folder the action should deploy.
          # '.' means the entire repository root.
          folder: .
          # The folder to deploy the files to in the target branch.
          # This will place your game in the /dice directory.
          target-folder: dice
          # Automatically remove files from the target folder that are not in the source folder.
          clean: true
